export const BOOKING_EXPIRATION_INTERVAL_SECONDS_ENV =
  'BOOKING_EXPIRATION_INTERVAL_SECONDS';
export const BOOKING_EXPIRATION_BATCH_SIZE_ENV =
  'BOOKING_EXPIRATION_BATCH_SIZE';

export const DEFAULT_BOOKING_EXPIRATION_INTERVAL_SECONDS = 60;
export const DEFAULT_BOOKING_EXPIRATION_BATCH_SIZE = 100;

export const MAX_BOOKING_EXPIRATION_INTERVAL_SECONDS = 3_600;
export const MAX_BOOKING_EXPIRATION_BATCH_SIZE = 1_000;
